### PR TITLE
Updated git url for gr-gsm.rb to v0.42.2

### PR DESCRIPTION
**Pull request by aldodelgado**
Was getting a 404 on the current git url version.

```└─[$] <> brew install dholm/sdr/gr-gsm
==> Installing gr-gsm from dholm/sdr
==> Downloading https://github.com/ptrkrysik/gr-gsm/archive/0.41.4git.tar.gz
==> Downloading from https://codeload.github.com/ptrkrysik/gr-gsm/tar.gz/0.41.4git

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "gr-gsm"
Download failed: https://github.com/ptrkrysik/gr-gsm/archive/0.41.4git.tar.gz```

### CODE REVIEW

**Comment by djerfy** [comment]
@aldodelgado Please update sha256 line too (`6127f87c1d295463c607a27cc2fc560e7a2b8684c1b0be10256db06936769976`)

**Comment by aldodelgado** [comment]
Sorry about that, missed it!

**Comment by thisconnect** [comment]
please review and merge

**Comment by thisconnect** [comment]
There is still a missing include, fixed and opened a PR in https://github.com/ptrkrysik/gr-gsm/pull/440

**Pull request closed without merging**
